import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { loadSigningProfile, type UserIdentity } from "@/lib/api-utils";
import { authClient } from "@/lib/auth-client";
import ky from "ky";
import { CheckCircle2, ExternalLink, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import z from "zod";
import NanopubEditor from "./components/NanopubEditor";
import { TEMPLATE_URI } from "./components/templates/registry-metadata";
import CreateModeTabs from "./CreateModeTabs";

/**
 * "Create Story" — publish a Science Live *story* nanopublication, pre-filled from
 * a `story-draft.json` produced by the replication repository's
 * `build_story_draft.py` (deterministic, no LLM tokens). A story is a narrative
 * COMPOSITION of a constellation: it references the record, pins the AI
 * plain-language summaries as audience tabs, and carries a hero image + evidence
 * figures. The author only reviews and edits the title + framing; everything else
 * flows through from the draft. Signing + publishing happen in-browser with the
 * user's own key (via the shared NanopubEditor), so the story lands on the Science
 * Live network under its own identity.
 *
 * Deep-link: `/np/create/story?draft=<url-of-story-draft.json>`.
 */

/**
 * The draft is fetched from a user-supplied URL, so it is untrusted input:
 * validate before rendering. Only the fields the story form reads are required;
 * descriptive metadata (`template`, `_notes`, …) is optional so a slightly older
 * or newer generator still loads.
 */
const summarySchema = z.object({
  uri: z.string(),
  audience: z.string().optional(),
  position: z.union([z.number(), z.string()]).optional(),
});
const figureSchema = z.object({
  contentUrl: z.string(),
  caption: z.string().optional(),
  doi: z.string().nullish(),
  about: z.string().nullish(),
  position: z.union([z.number(), z.string()]).optional(),
});
const heroSchema = z.object({
  contentUrl: z.string(),
  caption: z.string().optional(),
  doi: z.string().nullish(),
});
const storyDraftSchema = z.object({
  apex: z.string().min(1),
  headline: z.string().default(""),
  framing: z.string().default(""),
  summaries: z.array(summarySchema).default([]),
  hero: heroSchema.nullish(),
  figures: z.array(figureSchema).default([]),
});

type StoryDraft = z.infer<typeof storyDraftSchema>;

/**
 * A browser fetch of raw.githubusercontent.com is often blocked by CORS; the
 * jsDelivr GitHub mirror serves the same file with permissive CORS. Other URLs
 * pass through. (Same helper as the chain wizard.)
 */
function corsSafeUrl(url: string): string {
  const m = url.match(
    /^https:\/\/raw\.githubusercontent\.com\/([^/]+)\/([^/]+)\/([^/]+)\/(.+)$/,
  );
  return m
    ? `https://cdn.jsdelivr.net/gh/${m[1]}/${m[2]}@${m[3]}/${m[4]}`
    : url;
}

export default function StoryWizard() {
  const [searchParams, setSearchParams] = useSearchParams();
  const draftUrl = searchParams.get("draft");

  const [urlInput, setUrlInput] = useState(draftUrl ?? "");
  const [draft, setDraft] = useState<StoryDraft | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [publishedUri, setPublishedUri] = useState<string | null>(null);
  const [signingProfile, setSigningProfile] = useState<UserIdentity | null>(
    null,
  );
  const { data: session, isPending } = authClient.useSession();

  // Load the signing profile once a session is available (mirrors CreateNanopub).
  useEffect(() => {
    if (isPending || !session?.user) return;
    loadSigningProfile(setSigningProfile);
  }, [session, isPending]);

  // Fetch the story draft whenever the ?draft= URL changes.
  useEffect(() => {
    if (!draftUrl) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    ky.get(corsSafeUrl(draftUrl), { cache: "no-store" })
      .json<unknown>()
      .then((raw) => {
        if (cancelled) return;
        const parsed = storyDraftSchema.safeParse(raw);
        if (!parsed.success) {
          const issue = parsed.error.issues[0];
          const where = issue.path.length
            ? issue.path.join(".")
            : "the document";
          setDraft(null);
          setError(
            `That file is not a valid story draft (${where}: ${issue.message}). It should be a story-draft.json generated by your replication repository.`,
          );
          return;
        }
        setDraft(parsed.data);
        // A newly loaded draft starts unpublished (clear any prior success banner).
        setPublishedUri(null);
      })
      .catch((e) => {
        if (cancelled) return;
        let detail = e?.message ?? String(e);
        const res = e?.response as Response | undefined;
        if (res) detail = `HTTP ${res.status} ${res.statusText}`.trim();
        setError(
          `Could not load a story draft from that URL (${detail}). It should be a public story-draft.json — a jsDelivr or raw GitHub URL.`,
        );
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [draftUrl]);

  const identityPending =
    isPending || (!isPending && !!session?.user && !signingProfile);

  const loadFromInput = () => {
    const u = urlInput.trim();
    if (!u) return;
    const next = new URLSearchParams(searchParams);
    next.set("draft", u);
    setSearchParams(next);
  };

  return (
    <main className="container mx-auto flex grow flex-col gap-6 p-4 md:p-6 md:max-w-6xl">
      <CreateModeTabs />

      {!draft && (
        <Card className="max-w-2xl">
          <CardHeader>
            <CardTitle>Publish a story</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <p className="text-sm text-secondary-foreground">
              Load the <code>story-draft.json</code> from your replication
              repository. The story comes pre-filled — a title, framing, the
              audience-summary tabs, a hero image and the evidence figures, all
              composed from your constellation. Review, edit the title and
              framing, and publish.
            </p>
            <div className="flex flex-col gap-2 sm:flex-row">
              <Input
                value={urlInput}
                onChange={(e) => setUrlInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && loadFromInput()}
                placeholder="https://github.com/OWNER/REPO/…/nanopubs/story-draft.json"
                spellCheck={false}
                aria-label="Story draft URL"
              />
              <Button onClick={loadFromInput} disabled={loading}>
                {loading ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  "Load story"
                )}
              </Button>
            </div>
            {error && <p className="text-sm text-destructive">{error}</p>}
            <p className="text-xs text-muted-foreground">
              Tip: link straight here from your repository — a{" "}
              <code>…/np/create/story?draft=&lt;url&gt;</code> link opens the
              wizard already loaded.
            </p>
          </CardContent>
        </Card>
      )}

      {draft && (
        <>
          {publishedUri && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-green-600 dark:text-green-500">
                  <CheckCircle2 className="h-5 w-5" />
                  Story published
                </CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col gap-2">
                <code className="break-all text-sm">{publishedUri}</code>
                <a
                  href={`/np/?uri=${encodeURIComponent(publishedUri)}`}
                  className="inline-flex w-fit items-center gap-1 text-sm text-primary hover:underline"
                >
                  View the story <ExternalLink className="h-3.5 w-3.5" />
                </a>
              </CardContent>
            </Card>
          )}

          <NanopubEditor
            identity={signingProfile}
            identityPending={identityPending}
            templateUri={TEMPLATE_URI.STORY}
            prefilledData={draft}
            onPublished={(r) => setPublishedUri(r.uri)}
            embedded={false}
            hideAdvancedToggle
          />
        </>
      )}
    </main>
  );
}
