#!/usr/bin/env npx tsx
/**
 * Generate TypeScript declaration files for SPARQL query files (.rq).
 *
 * This script parses .rq files in src/lib/queries/ and generates corresponding
 * .rq.d.ts files with typed placeholder information based on comment annotations.
 *
 * Placeholder format in .rq files:
 *   # Placeholder: `?_placeholderName` - description
 *   # Placeholder: `?_placeholderName` - URI: description (for URI type)
 *   # Placeholder: `?_placeholderName` - RAW: description (for RAW type)
 *
 * Type inference:
 *   - If comment contains "URI:" → "uri" type
 *   - If comment contains "RAW:" → "raw" type
 *   - Otherwise → "literal" type
 */

import * as fs from "fs";
import { glob } from "glob";
import * as path from "path";

const QUERIES_DIR = "src/lib/queries";

interface Placeholder {
  name: string;
  type: "uri" | "literal" | "raw";
}

/**
 * Parse a SPARQL query file and extract placeholder information from comments.
 */
function parseQueryFile(content: string): {
  description: string;
  placeholders: Placeholder[];
} {
  const lines = content.split("\n");
  const descriptionLines: string[] = [];
  const placeholders: Placeholder[] = [];
  let endedDescription = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // Extract description from leading comment lines
    if (
      trimmed.startsWith("#") &&
      !trimmed.includes("Placeholder:") &&
      !endedDescription
    ) {
      const commentText = trimmed.slice(1).trim();
      // Skip prefix declarations in comments
      if (!commentText.startsWith("prefix ") && commentText.length > 0) {
        descriptionLines.push(commentText);
      }
    } else {
      endedDescription = true;
    }

    // Parse placeholder annotations
    if (trimmed.startsWith("#") && trimmed.includes("Placeholder:")) {
      const placeholderMatch = trimmed.match(
        /Placeholder:\s*`?\?_([^`:\s]+)`?\s*[-—:]\s*(.*)/i,
      );
      if (placeholderMatch) {
        const name = placeholderMatch[1];
        const description = placeholderMatch[2].trim();

        // Determine type based on description content
        let type: "uri" | "literal" | "raw" = "literal";
        if (description.toUpperCase().includes("URI:")) {
          type = "uri";
        } else if (description.toUpperCase().includes("RAW:")) {
          type = "raw";
        }

        placeholders.push({ name, type });
      }
    }
  }

  return {
    description: descriptionLines.join(" ").trim() || "SPARQL query",
    placeholders,
  };
}

/**
 * Generate TypeScript declaration content for a query file.
 */
function generateDeclaration(
  queryFileName: string,
  description: string,
  placeholders: Placeholder[],
): string {
  const baseName = path.basename(queryFileName, ".rq");

  // Build the placeholder type object
  const placeholderType =
    placeholders.length > 0
      ? `{\n${placeholders.map((p) => `  ${p.name}: "${p.type}";`).join("\n")}\n}`
      : "Record<string, never>";

  // Generate the description, capitalizing first letter
  const capitalizedDescription =
    description.charAt(0).toUpperCase() + description.slice(1);

  return `/**
 * ${capitalizedDescription}
 * @see ./${baseName}.rq
 * @generator Generated by \`npm run generate:query-types\`
 */
declare const query: import("../sparql").SparqlQuery<${placeholderType}>;
export default query;
`;
}

/**
 * Main function to generate all declaration files.
 */
async function main() {
  console.log("Generating SPARQL query type declarations...\n");

  // Find all .rq files
  const pattern = path.join(QUERIES_DIR, "*.rq").replace(/\\/g, "/");
  const queryFiles = await glob(pattern);

  if (queryFiles.length === 0) {
    console.log("No .rq files found in", QUERIES_DIR);
    return;
  }

  let generated = 0;
  let skipped = 0;

  for (const queryFile of queryFiles) {
    const declarationFile = `${queryFile}.d.ts`;
    // const relativeQueryFile = path.relative(process.cwd(), queryFile);
    const relativeDeclFile = path.relative(process.cwd(), declarationFile);

    // Read and parse the query file
    const content = fs.readFileSync(queryFile, "utf-8");
    const { description, placeholders } = parseQueryFile(content);

    // Generate declaration content
    const declaration = generateDeclaration(
      queryFile,
      description,
      placeholders,
    );

    // Check if file exists and has same content
    if (fs.existsSync(declarationFile)) {
      const existing = fs.readFileSync(declarationFile, "utf-8");
      if (existing === declaration) {
        console.log(`  [skip] ${relativeDeclFile} (up to date)`);
        skipped++;
        continue;
      }
    }

    // Write the declaration file
    fs.writeFileSync(declarationFile, declaration, "utf-8");
    console.log(`  [gen]  ${relativeDeclFile}`);
    if (placeholders.length > 0) {
      console.log(
        `         Placeholders: ${placeholders.map((p) => `${p.name}: ${p.type}`).join(", ")}`,
      );
    }
    generated++;
  }

  console.log(`\nDone! Generated: ${generated}, Skipped: ${skipped}`);
}

main().catch((err) => {
  console.error("Error generating query types:", err);
  process.exit(1);
});
