// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-attach-nanopub-label'
  | 'menuitem-create-nanopub-label'
  | 'menuitem-file-import-attach-label'
  | 'menuitem-file-import-new-label'
  | 'menuitem-search-nanopub-label'
  | 'pref-about'
  | 'pref-help'
  | 'pref-help-orcid'
  | 'pref-help-sign'
  | 'pref-name'
  | 'pref-orcid'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
