// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-attach-nanopub-label'
  | 'menuitem-create-nanopub-submenu'
  | 'menuitem-custom-label'
  | 'menuitem-file-import-attach-label'
  | 'menuitem-file-import-new-label'
  | 'menuitem-search-nanopub-label'
  | 'pref-about'
  | 'pref-about-profile'
  | 'pref-api-key'
  | 'pref-help'
  | 'pref-test-connection'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
