/**
 * Get the nanopub(s) that assert a given AIDA-statement IRI (`http://purl.org/aida/<sentence>`), i.e. the AIDA Sentence nanopub. A FORRT Claim links to its AIDA only through this shared statement IRI (`sciencelive:asAidaStatement <aida-IRI>`), never by the AIDA's nanopub URI. Neither the npa:refersToNanopub index nor TriG URI-mining can reach the AIDA nanopub from the Claim, so the constellation walk uses this query to bridge Claim -> AIDA (and from the AIDA, the upstream Quote follows via skos:related).
 * @see ./aida-statement-nanopub.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  aidaStatementIri: "uri";
}, {
  np: "string";
  label: "string";
  date: "string";
  creator: "string";
  template: "string";
}>;
export default query;
