/**
 * Display names (foaf:name) for a set of creator ORCID URIs. A constellation's node label, date and creator are captured from the reference-discovery queries during the walk; only the human-readable creator name still needs a lookup. A constellation has just a handful of distinct authors, so this stays a small, fast query.
 * @see ./creator-names.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  uris: "raw";
}, {
  orcid: "string";
  name: "string";
}>;
export default query;
