/**
 * Comprehensive query to get all location information with provenance. Optionally filter by bounding box area and/or search term.
 * @see ./geolocation.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  searchTerm: "literal";
  bboxMinX: "literal";
  bboxMinY: "literal";
  bboxMaxX: "literal";
  bboxMaxY: "literal";
}>;
export default query;
