/**
 * Comprehensive query to get all location information with provenance. Optionally filter by bounding box area and/or search term.
 * @see ./geolocation.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  searchTerm: "literal";
  bboxMinX: "literal";
  bboxMinY: "literal";
  bboxMaxX: "literal";
  bboxMaxY: "literal";
}, {
  np: "string";
  paper: "string";
  location: "string";
  location_label: "string";
  date: "string";
  wkt: "string";
  bbox: "string";
  quotation: "string";
  quotation_end: "string";
  comment: "string";
  creator: "string";
}>;
export default query;
