/**
 * Comprehensive query to get all location information with provenance.
 * @see ./geolocation.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<Record<string, never>>;
export default query;
