/**
 * Barrel export for all SPARQL query files.
 *
 * @generator Generated by `npm run generate:query-types`
 */

export { default as GEOLOCATION } from "./geolocation.rq";
export { default as LATEST_BY_TEMPLATE } from "./latest-by-template.rq";
export { default as LATEST_BY_TEMPLATES } from "./latest-by-templates.rq";
export { default as NANOPUB_COMMENTS } from "./nanopub-comments.rq";
export { default as NANOPUB_REFERENCES } from "./nanopub-references.rq";
export { default as NANOPUB_STATUS } from "./nanopub-status.rq";
export { default as SEARCH_NANOPUBS } from "./search-nanopubs.rq";
export { default as SEARCH_NANOPUBS_BY_TYPE } from "./search-nanopubs-by-type.rq";
export { default as SEARCH_RELATED_NANOPUBS } from "./search-related-nanopubs.rq";
export { default as USERS_LATEST } from "./users-latest.rq";
