/**
 * Get the latest nanopublications created from any of the given templates. Excludes invalidated and superseded nanopubs. Use this for templates with legacy versions (e.g. AIDA Sentence, FORRT Claim).
 * @see ./latest-by-templates.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  templateValues: "raw";
  sortBy: "raw";
  limit: "raw";
  offset: "raw";
}, {
  description: "string";
  referenceCount: "string";
  np: "string";
  label: "string";
  date: "string";
  creator: "string";
  type: "string";
  template: "string";
}>;
export default query;
