/**
 * Get the latest nanopublications created from a specific template. Excludes invalidated and superseded nanopubs.
 * @see ./latest-by-template.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  templateUri: "uri";
}, {
  np: "string";
  label: "string";
  date: "string";
  creator: "string";
}>;
export default query;
