/**
 * Get the latest nanopublications created from any of the given templates. Excludes invalidated and superseded nanopubs. Use for templates with legacy versions.
 * @see ./latest-by-templates.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  templateValues: "raw";
}, {
  np: "string";
  label: "string";
  date: "string";
  creator: "string";
  description: "string";
}>;
export default query;
