/**
 * Get the latest nanopublications regardless of template type. Excludes invalidated and superseded nanopubs.
 * @see ./latest-all.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  sortBy: "raw";
  limit: "raw";
  offset: "raw";
}, {
  description: "string";
  referenceCount: "string";
  np: "string";
  label: "string";
  date: "string";
  creator: "string";
  type: "string";
  template: "string";
}>;
export default query;
