/**
 * Get all nanopub types for a given nanopublication. Returns the type URIs associated with the specified nanopub via npx:hasNanopubType.
 * @see ./nanopub-types.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  nanopubUri: "uri";
}, {
  type: "string";
}>;
export default query;
