/**
 * Get the label for a nanopub URI from the nanopub network. Returns the rdfs:label registered in the admin graph for the specified nanopub.
 * @see ./nanopub-label.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  nanopubUri: "uri";
}, {
  label: "string";
}>;
export default query;
