/**
 * Get the labels of all nanopubs referred to within a specified nanopub. Uses npa:networkGraph to efficiently find outgoing references.
 * @see ./nanopub-refers-to.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  nanopubUri: "uri";
}, {
  refNanopub: "string";
  label: "string";
}>;
export default query;
