/**
 * Get all nanopubs that refer to a specified nanopub URI. Uses npa:networkGraph to efficiently find references. Excludes invalidated and superseded nanopubs. Also excludes comments, retractions and approval/disapproval.
 * @see ./nanopub-references.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  nanopubUri: "uri";
}, {
  description: "string";
  np: "string";
  label: "string";
  date: "string";
  creator: "string";
  template: "string";
}>;
export default query;
