/**
 * Retrieve all comments for a given nanopublication. A comment nanopub has rdfs:comment as predicate with the nanopubUri as object. Returns the comment nanopub URI, the comment text, creator, and creation date.
 * @see ./nanopub-comments.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  nanopubUri: "uri";
}, {
  commentNp: "string";
  commentText: "string";
  creator: "string";
  createdDate: "string";
}>;
export default query;
