/**
 * Get the labels for a set of nanopub URIs from the nanopub network. Uses a VALUES clause to efficiently look up multiple labels in a single query.
 * @see ./nanopub-labels.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  nanopubUris: "raw";
}, {
  nanopubUri: "string";
  label: "string";
}>;
export default query;
