/**
 * Get status attributes for a nanopublication. Returns the latest supersedes, latest retracts, approvals count, disapprovals count, and comments count.
 * @see ./nanopub-status.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  nanopubUri: "uri";
}, {
  supercededBy: "string";
  retractedBy: "string";
  approvals: "string";
  disapprovals: "string";
  comments: "string";
}>;
export default query;
