/**
 * Get all nanopubs that the specified nanopub references (the inverse direction of nanopub-references.rq). Uses the KP admin networkGraph which materialises npa:refersToNanopub edges from each nanopub's triples — so finding what a nanopub points at is a single hop.
 * @see ./references-from.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  nanopubUri: "uri";
}, {
  np: "string";
  label: "string";
  date: "string";
  creator: "string";
  template: "string";
}>;
export default query;
