/**
 * Every independent replication of a paper's claims, with the verdict each reached. Enumerates by the CiTO->DOI method: a replication Outcome makes a verdict-citation (cito:confirms / qualifies / disputes / …) to the original paper's DOI. This is the reliable "all replications of paper X" set — unlike a graph BFS from the paper, which bleeds into adjacent chains and misses disconnected replications. Each matching Outcome is then walked up its FORRT chain for display: Outcome  -> verdict, confidence, conclusion, deposit repository isOutcomeOf -> Study  -> label, scope, methodology, deviations targetsClaim -> Claim -> label, AIDA statement (the atomic claim sentence), FORRT type Outcomes that have been retracted / invalidated / superseded by their own signer are excluded via the admin graph (npx:invalidates covers retract + supersede; the matching public-key hash ensures only the original signer can retract their own work — a third party cannot suppress someone else's outcome). Disapproval is deliberately not a filter.
 * @see ./replications-by-paper.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  doiUri: "uri";
}, {
  outcome: "string";
  status: "string";
  rel: "string";
  confidence: "string";
  conclusion: "string";
  repo: "string";
  study: "string";
  studyLabel: "string";
  scope: "string";
  method: "string";
  deviation: "string";
  claim: "string";
  claimLabel: "string";
  aida: "string";
  ctype: "string";
}>;
export default query;
