/**
 * Full-text search on nanopub labels. Excludes invalidated, superseded, and template nanopubs.
 * @see ./search-nanopubs.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  searchTerm: "literal";
}, {
  referenceCount: "string";
  maxScore: "string";
  np: "string";
  label: "string";
  date: "string";
  creator: "string";
  isExample: "string";
  template: "string";
}>;
export default query;
