/**
 * Search for nanopubs of a specific RDF type. Excludes invalidated and superseded nanopubs.
 * @see ./search-nanopubs-by-type.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  searchTerm: "literal";
  rdfType: "uri";
}, {
  thing: "string";
  label: "string";
}>;
export default query;
