/**
 * Get related nanopubs. Search for nanopubs which mention the specified nanopubUri.
 * @see ./search-related-nanopubs.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  nanopubUri: "uri";
}, {
  np: "string";
}>;
export default query;
