/**
 * Full-text search on nanopub labels or all literal fields, filtered by template. Excludes example, invalidated, and superseded. Only returns nanopubs created from one of the provided templates.
 * @see ./search-nanopubs-by-templates.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  searchTerm: "literal";
  searchProperty: "raw";
  templateValues: "raw";
  limit: "raw";
  offset: "raw";
  sortBy: "raw";
}, {
  referenceCount: "string";
  maxScore: "string";
  np: "string";
  label: "string";
  date: "string";
  creator: "string";
  type: "string";
  template: "string";
}>;
export default query;
