/**
 * Full-text search on nanopub labels or all literal fields. Excludes example, invalidated, superseded, and template nanopubs.
 * @see ./search-nanopubs.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  searchTerm: "literal";
  searchProperty: "raw";
  limit: "raw";
  offset: "raw";
  sortBy: "raw";
}, {
  types: "string";
  description: "string";
  referenceCount: "string";
  maxScore: "string";
  np: "string";
  label: "string";
  date: "string";
  creator: "string";
  template: "string";
}>;
export default query;
