# Get the latest nanopublications created by the user with the specified ORCID URI.
# Excludes invalidated, superseded, and template nanopubs.
#
# Placeholder: `?_orcidUri` - URI: the user's ORCID.

prefix pc: <http://purl.org/petapico/o/paperclub#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dct: <http://purl.org/dc/terms/>
prefix np: <http://www.nanopub.org/nschema#>
prefix npa: <http://purl.org/nanopub/admin/>
prefix npx: <http://purl.org/nanopub/x/>

select ?np ?label ?date where {
graph npa:graph {
    ?np npa:hasValidSignatureForPublicKeyHash ?pubkey .
    filter not exists { ?npx npx:invalidates ?np ; npa:hasValidSignatureForPublicKeyHash ?pubkey . }
    ?np dct:created ?date ;
        rdfs:label ?label ;
        dct:creator ?_orcidUri .
}
} order by desc(?date) limit 10
