/**
 * Get the latest nanopublications created by the user with the specified ORCID URI. Excludes invalidated, superseded, and template nanopubs.
 * @see ./users-latest.rq
 * @generator Generated by `npm run generate:query-types`
 */
declare const query: import("../sparql").SparqlQuery<{
  orcidUri: "uri";
}, {
  paper: "string";
  comment: "string";
  label: "string";
  np: "string";
  date: "string";
}>;
export default query;
