/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 7e4676034c2199aaeb4e67a02aa0fac7)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		HYPERDRIVE: Hyperdrive;
		PORT: string;
		FRONTEND_URL: string;
		API_URL: string;
		BETTER_AUTH_SECRET: string;
		ENCRYPTION_KEY: string;
		DATABASE_URL: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		WRANGLER_SEND_METRICS: string;
		ORCID_CLIENT_ID: string;
		ORCID_CLIENT_SECRET: string;
		RESEND_API_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PORT" | "FRONTEND_URL" | "API_URL" | "BETTER_AUTH_SECRET" | "ENCRYPTION_KEY" | "DATABASE_URL" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID" | "WRANGLER_SEND_METRICS" | "ORCID_CLIENT_ID" | "ORCID_CLIENT_SECRET" | "RESEND_API_KEY">> {}
}
